### PR TITLE
Support data references in render tag.

### PR DESCRIPTION
**Pull request by das-peter**
Use `getContext()` to fetch `innerContext` in order to trigger the data reference handling.

### CODE REVIEW

**Comment by Chapabu** [comment]
Is there an issue that supports this change? The code change looks fine, but with no background information on the PR (or a linked issue) I'm a bit apprehensive to merge.

**Comment by das-peter** [comment]
There's no issue yet.
As for background info:  
The documentation describes how to use [data references](https://fractal.build/guide/core-concepts/context-data.html#static-data-references) but this doesn't work as documented if you use the [render tag](https://github.com/frctl/twig#render) because the implementation accesses the context data directly instead using the available API - which is where the data reference handling is implemented.
So in order to make the render tags data processing work as documented we need to slightly adjust the code of its implementation to use the available API.

Is that background enough? I don't have a simple example at hand atm. but if necessary could create something.

**Comment by mihkeleidast** [comment]
I tried to recreate the issue at https://github.com/risker/fractal-demo-project/tree/demo/pull-31

if i understood the problem correctly:
- we have three components, `@a`, `@b`, `@c`.
- `@b` references the context of `@a` in its context object
- `@c` tries to use the `render` tag to render `@b`, which, in order to render, needs to resolve `@a` to correct context object.

this does give me an error for rendering `@c`. unfortunately, the change in this PR does not fix the render error.

if i misunderstood the issue (and found another unrelated bug), could you provide an example that would be fixed by this change?

**Review by mihkeleidast — APPROVED** [review]
Today I discovered that I was getting an error since twig.js 1.14.0 broke the render tag for all usecases. Following a fix for that one (#35), I've successfully reproduced this issue.

Without this fix, per my previous example, data reference for `@a` was not resolved, and this change fixes that.

Thanks for the fix!

**Comment by das-peter** [comment]
@risker Thank you very much for your pro-active evaluation - much appreciated!

**Pull request merged**
